version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db_dteng
      - MYSQL_USER=user_dteng
      - MYSQL_PASSWORD=cirilgroupt
    ports:
      - "3306:3306"
    restart: always

  schema-python:
    image: schema-python
    build: images/schema-python
    command: sh -c "sleep 10s ; python3 ./schema.py"
    volumes:
      - ./data:/data
    depends_on:
      - database

  sort-python:
    image: sort-python
    build: images/sort-python
    command: sh -c "sleep 10s ; python3 ./sort.py"
    volumes:
      - ./data:/data
    depends_on:
      - database
